In [10]:
import json
import pandas as pd
# File to load
food_data_raw = "Google Places API Burgers.json"

with open(food_data_raw,mode='r') as data:
    f = json.load(data)
    # print(json.dumps(f,indent=2))
    print(f['results'][0])
    # this would be one record
    # food_data_df = pd.read_json(f['results'],orient='records')
    
# print(food_data_raw[-5:])

# print(f)
# Read the data


# food_data_df.head()

{'business_status': 'OPERATIONAL', 'geometry': {'location': {'lat': 44.0225036, 'lng': -92.4637066}, 'viewport': {'northeast': {'lat': 44.02392197989271, 'lng': -92.46241624999998}, 'southwest': {'lat': 44.02122232010727, 'lng': -92.46520124999999}}}, 'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/restaurant-71.png', 'icon_background_color': '#FF9E67', 'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/restaurant_pinlet', 'name': "Chester's Kitchen & Bar", 'opening_hours': {'open_now': True}, 'photos': [{'height': 3024, 'html_attributions': ['<a href="https://maps.google.com/maps/contrib/102589600606094975192">Marzouq Alghanim</a>'], 'photo_reference': 'Aap_uEB3TVEvhkrXl-4bmsu9Wc3c009cWdAU-lT8AqGgsCKvkA5SZqXogpWzjrTigEXL5ox_4qnY0wCT-B0px_qSNYzeufI-A0X-_ZPh_UgR4_qAstwQSdzsJZbo3Ki8yZnD409ESrPOngebCnwK4iXOjzqkxKZ2O89X7fAtGgtQYzuLN-8V', 'width': 4032}], 'place_id': 'ChIJi-0g1nxf94cRCY5hpn6YerA', 'plus_code': {'compound_code': '2GFP+2G Rochester, Minnesota', 'global_code': '86P92GFP+2G'}, 'price_level': 2, 'rating': 4.5, 'reference': 'ChIJi-0g1nxf94cRCY5hpn6YerA', 'scope': 'GOOGLE', 'types': ['bar', 'restaurant', 'food', 'point_of_interest', 'establishment'], 'user_ratings_total': 1328, 'vicinity': 'Shops At University Square, 111 Broadway Ave S #108, Rochester'}

In [13]:
f['results'][0].keys()

dict_keys(['business_status', 'geometry', 'icon', 'icon_background_color', 'icon_mask_base_uri', 'name', 'opening_hours', 'photos', 'place_id', 'plus_code', 'price_level', 'rating', 'reference', 'scope', 'types', 'user_ratings_total', 'vicinity'])

In [14]:

df_columns = [
'rating',
'geometry',
'price_level',
'name',
'types']

In [29]:
columns = []
for row in f['results']:
    # print(row)
    try:
        pandas_data = {
        'rating' : row['rating'],
        'latitude' : row['geometry']['location']['lat'],
        'longitude' : row['geometry']['location']['lng'],
        
        'price_level' : row['price_level'],
        
        'name' : row['name'],
        'types' : row['types'][0]
        }
    except:
        pass
    columns.append(pandas_data)

In [30]:
print(columns)
pd.DataFrame(columns)

[{'rating': 4.5, 'latitude': 44.0225036, 'longitude': -92.4637066, 'price_level': 2, 'name': "Chester's Kitchen & Bar", 'types': 'bar'}, {'rating': 4.5, 'latitude': 44.0202128, 'longitude': -92.46424019999999, 'price_level': 2, 'name': 'The Half Barrel', 'types': 'bar'}, {'rating': 4.5, 'latitude': 44.0202411, 'longitude': -92.4636338, 'price_level': 2, 'name': 'The Tap House', 'types': 'bar'}, {'rating': 4.4, 'latitude': 44.0217773, 'longitude': -92.4836972, 'price_level': 2, 'name': 'Saints On 2nd', 'types': 'restaurant'}, {'rating': 4.3, 'latitude': 44.0268209, 'longitude': -92.48678290000001, 'price_level': 2, 'name': "Wild Bill's Sports Saloon - Rochester", 'types': 'restaurant'}, {'rating': 4.4, 'latitude': 44.021, 'longitude': -92.46414000000001, 'price_level': 2, 'name': "Newt's", 'types': 'restaurant'}, {'rating': 4.4, 'latitude': 44.021, 'longitude': -92.46414000000001, 'price_level': 2, 'name': "Newt's", 'types': 'restaurant'}, {'rating': 4.4, 'latitude': 44.021, 'longitude': -92.46414000000001, 'price_level': 2, 'name': "Newt's", 'types': 'restaurant'}, {'rating': 3.8, 'latitude': 44.0264181, 'longitude': -92.48671780000001, 'price_level': 1, 'name': "Denny's", 'types': 'restaurant'}, {'rating': 4.5, 'latitude': 44.02187, 'longitude': -92.4815517, 'price_level': 2, 'name': 'Canadian Honker Restaurant', 'types': 'restaurant'}, {'rating': 3.1, 'latitude': 44.03864919999999, 'longitude': -92.46164089999999, 'price_level': 1, 'name': 'Burger King', 'types': 'restaurant'}, {'rating': 4.5, 'latitude': 44.0141808, 'longitude': -92.4624999, 'price_level': 1, 'name': 'Brothers Bar & Grill', 'types': 'bar'}, {'rating': 3.5, 'latitude': 44.0219128, 'longitude': -92.4855455, 'price_level': 1, 'name': "McDonald's", 'types': 'cafe'}, {'rating': 4.6, 'latitude': 44.0190182, 'longitude': -92.4637011, 'price_level': 3, 'name': 'Bleu Duck Kitchen', 'types': 'bar'}, {'rating': 4.2, 'latitude': 44.0238318, 'longitude': -92.48683439999999, 'price_level': 2, 'name': 'The Boulder Tap House - Rochester', 'types': 'restaurant'}, {'rating': 4.4, 'latitude': 44.0212631, 'longitude': -92.4932632, 'price_level': 2, 'name': 'Beetles Bar & Grill', 'types': 'bar'}, {'rating': 4.4, 'latitude': 44.0212631, 'longitude': -92.4932632, 'price_level': 2, 'name': 'Beetles Bar & Grill', 'types': 'bar'}, {'rating': 4.4, 'latitude': 44.0212631, 'longitude': -92.4932632, 'price_level': 2, 'name': 'Beetles Bar & Grill', 'types': 'bar'}]

,rating,latitude,longitude,price_level,name,types
0,4.5,44.022504,-92.463707,2,Chester's Kitchen & Bar,bar
1,4.5,44.020213,-92.464240,2,The Half Barrel,bar
2,4.5,44.020241,-92.463634,2,The Tap House,bar
3,4.4,44.021777,-92.483697,2,Saints On 2nd,restaurant
4,4.3,44.026821,-92.486783,2,Wild Bill's Sports Saloon - Rochester,restaurant
5,4.4,44.021000,-92.464140,2,Newt's,restaurant
6,4.4,44.021000,-92.464140,2,Newt's,restaurant
7,4.4,44.021000,-92.464140,2,Newt's,restaurant
8,3.8,44.026418,-92.486718,1,Denny's,restaurant
9,4.5,44.021870,-92.481552,2,Canadian Honker Restaurant,restaurant
10,3.1,44.038649,-92.461641,1,Burger King,restaurant
11,4.5,44.014181,-92.462500,1,Brothers Bar & Grill,bar
12,3.5,44.021913,-92.485546,1,McDonald's,cafe
13,4.6,44.019018,-92.463701,3,Bleu Duck Kitchen,bar
14,4.2,44.023832,-92.486834,2,The Boulder Tap House - Rochester,restaurant
15,4.4,44.021263,-92.493263,2,Beetles Bar & Grill,bar
16,4.4,44.021263,-92.493263,2,Beetles Bar & Grill,bar
17,4.4,44.021263,-92.493263,2,Beetles Bar & Grill,bar